config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'static_pages/help'

  namespace :admin do
    resources :movies do
      post 'change_status', on: :member
    end
    resources :theatres, :shows
    resources :dashboards, only: [:index]
  end

  resources :movies, only: %i[index show]
  resources :tickets, :movie_interests, except: %i[new edit update]
  resources :reviews, except: %i[edit update]
  devise_for :users, controllers: { registrations: 'myregistrations' }

  resources :users do
    member do
      get 'activate_account'
      get 'activate_user_account'
      post 'activate_account_mail'
    end
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :requires_admin
  before_action :set_admin_movie, only: %i[show edit update destroy change_status]
  after_action :send_users_notif, only: %i[change_status]

  def index
    @admin_movies = Movie.all.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render :show }
      format.js {}
    end
  end

  def new
    @admin_movie = Movie.new
  end

  def edit; end

  def create
    @admin_movie = Movie.new(admin_movie_params)
    respond_to do |format|
      if @admin_movie.save
        format.html { redirect_to admin_movies_url, notice: 'Movie was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_movie.update(admin_movie_params)
        format.html { redirect_to admin_movies_url, notice: 'Movie details Updated' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @admin_movie.shows.blank? && @admin_movie.reviews.blank?
        @admin_movie.destroy
        format.html { redirect_to admin_movies_url, notice: 'Movie was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_movies_url, notice: 'Movie cannot be deleted.' }
        format.json { head :no_content }
      end
    end
  end

  def change_status
    @admin_movie.status = 'Now Showing'
    respond_to do |format|
      if @admin_movie.save
        flash[:notice] = 'Successfully updated to Now Showing '
        format.html { redirect_to admin_movies_url }
      end
    end
  end

  private
  

  def set_admin_movie
    @admin_movie = Movie.find(params[:id])
  end

  def admin_movie_params
    params.require(:admin_movie).permit(:name, :summary, :status, :image)
  end

  def send_users_notif
    UserMailer.movie_update(@admin_movie.id.to_s).deliver_later
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :requires_non_admin

  def index
    @movies = Movie.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    @movie = Movie.find(params[:id])
    @shows = Show.where(movie_id: @movie.id).paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
<div class= "row">
  <div class="col-md-4 col-md-offset-4">
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      
      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
</div>
<% end %>

app/views/movies/index.html.erb
<%= will_paginate @movies %>
<h1>Movies</h1>

<body>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Summary</th>
        <th>Status </th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.name %></td>
          <td><%= movie.summary %></td>
          <td><%= movie.status %></td>
          <% if movie.status == "Now Showing" %>
            <td><%= link_to 'Book', movie, class: 'btn btn-primary btn-lg' %></td>
            <% if current_user.role == "critic" %>
              <td><%= link_to "Review", new_review_path(:id => movie.id) %></td>
            <% end %>
          <% else %>
            <td><%= link_to 'Subscribe', movie_interests_path(:movie_id => movie.id), method: :post, class: 'btn btn-primary btn-lg' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<br />
<%= will_paginate @movies %>

app/views/movies/show.html.erb
<%= will_paginate @shows %>
<script>
  function calc_total_cost(ele) {
  var x = $(ele).closest('#movie_show_row').find('input.ticket_temp').val();
  $(ele).closest('#movie_show_row').find('input.total_cost').val($(ele).val()*x);
}
</script>
<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <td><%= @movie.name %></td>
    </tr>
    <tr>
      <th>Summary</th>
      <td><%= @movie.summary %></td>
    </tr>
  </thead>
  <% if @movie.status == "Now Showing" %>
    <% if @shows.any? %>
      <table>
        <thead>
          <tr>
            <th>Theatre Name</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Cost per Seat</th>
            <th>Number of seats</th>
            <th>Total Cost</th>
          </tr>
        </thead>
        <tbody>
          <% @shows.each do |show| %>
            <tr id="movie_show_row">
              <% if show.booking_state == "vacant" %>
                <%= form_for(:ticket, :url => url_for(action: 'create', controller:'tickets')) do |f| %>
                  <%= f.hidden_field :show_id, value: show.id %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <td><%= show.theatre.name %></td>
                  <td><%= show.start_time %></td>
                  <td><%= show.end_time %></td>
                  <td><%= f.number_field :temp, class: "ticket_temp", value:show.cost_per_seat, readonly: true %></td>
                  <td><%= f.number_field(:num_seats_bought, min: 1 , max: (show.total_seats - show.num_seats_sold), step: 1, onchange: "calc_total_cost(this)") %>
                  <td><%= f.text_field :total_cost, class: "total_cost", readonly: true %></td>
                  <td>
                    <div class="actions">
                      <td><%= f.submit "Book Tickets", class: "submit_btn" %></td>
                    </div>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <br />
      <p> No shows yet </p>
    <% end %>
  <% end %>
</table>
<%= link_to 'Back', movies_path %>
<%= will_paginate @shows %>