config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'static_pages/help'

  namespace :admin do
    resources :movies do
      post 'change_status', on: :member
    end
    resources :theatres, :shows
    resources :dashboards, only: [:index]
  end

  resources :movies, only: %i[index show]
  resources :tickets, :movie_interests, except: %i[new edit update]
  resources :reviews, except: %i[edit update]
  devise_for :users, controllers: { registrations: 'myregistrations' }

  resources :users do
    member do
      get 'activate_account'
      get 'activate_user_account'
      post 'activate_account_mail'
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
  #Scopes       
  scope :inactive, -> { where(active: false) }

  #Fields
  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Customized
  field :name, type: String
  field :role, type: String, default: 'customer'
  field :active, type: Boolean, default: true

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  field :locked_at,       type: Time


  #Indexes
  index({ email: 1 }, unique: true)
  index({ reset_password_token: 1 }, unique: true)
  index({ confirmation_token: 1 }, unique: true)
  index({ unlock_token: 1 }, unique: true)

  #Database associations
  has_many :tickets
  has_many :reviews
  has_many :movie_interests

  #Validations
  validates :name, presence: true, length: { minimum: 3, maximum: 40 }
  validates :encrypted_password, presence: true, confirmation: true
  validates :role, :active, presence: true
  validates :email, presence: true, length: { maximum: 255 }
  
  #Callbacks
  after_create :user_registration_email

  #Methods
  def user_registration_email
    UserMailer.welcome_email(id.to_s).deliver_later
  end

  def active_for_authentication?
    super && self.active?
  end

  def inactive_message
    'Sorry, this account has been deactivated. Sign up and activate account' if !self.active?
    'Confirmation mail sent'
  end

  protected

  #Explicit definition of devise method required since it is used in the callbacks and defined for ActiveRecord but not for Mongoid otherwise it throws an undefined method error
  def will_save_change_to_email?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource :user
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all.paginate(page: params[:page], per_page: 10)
  end

  def show; end

  def edit
    @user = if params[:id].nil?
              current_user
            else
              User.find_by(id: params[:id])
            end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @user.role == 'admin'
      @users = User.where(role: 'admin')
      respond_to do |format|
        if @users.count >= 2
          if @user.destroy
            sign_out @user
            format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
            format.json { head :no_content }
          end
        else
          flash[:error] = 'Cannot delete account since you are the only admin!'
          format.html { redirect_back(fallback_location: admin_movies_url) }
          format.json { head :no_content }
        end
      end
    else
      @user.active = false
      respond_to do |format|
        if @user.update
          sign_out @user
          format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        else
          flash[:error] = 'Error deleting user'
          format.html { redirect_back(fallback_location: movies_url) }
          format.json { head :no_content }
        end
      end
    end
  end

  def activate_account
    @user = User.find(id: params[:id])
    render 'activate_account'
  end

  def activate_account_mail
    UserMailer.activate_user_account(params[:id],params[:user][:email]).deliver_now
    flash[:notice] = 'Email sent. Please check your mail'
    redirect_to root_url
  end

  def activate_user_account
    @user = User.where(id: params[:id]).first
    if @user
      @user.active = true
      flash[:notice] = 'Account activated. You  can now login.' if @user.save
      redirect_to new_user_session_url
    else
      redirect_to root_url
    end
  end

  private
  

  def set_user
    @user = if params[:id] == 'sign_out'
              User.find(current_user.id)
            else
              User.find(params[:id])
            end
  end

  def role?
    role == current_user.role
  end

  def user_params
    if current_user.role == 'admin'
      params.require(:user).permit(:name, :email, :role)
    else
      params.fetch(:user, {})
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/activate_account.html.erb
<h2>Account already exists.</h2>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    Send email to activate account?
    <div class="form-horizontal">
      <%= form_for(:user, url: activate_account_mail_user_path(@user)) do |f| %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" , class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit "Send Link" , class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="form-horizontal">
      <%= render 'form', user: @user %>
      <%= form_for(@user) do |f| %>
        <div class="field">
          <%= f.label :name %>
          <% if current_user.role == "admin" %>
            <%= f.text_field :name, :readonly => true, class: 'form-control' %>
          <% else %>
            <%= f.text_field :name, class: 'form-control' %>
          <% end %>
        </div>

        <div class="field">
          <%= f.label :email %>
          <% if current_user.role == "admin" %>
            <%= f.text_field :email, :readonly => true , class: 'form-control' %>
          <% else %>
            <%= f.text_field :email, class: 'form-control' %>
          <% end %>
        </div>

        <div class="field">
          <%= f.radio_button :role, 'customer', class: 'form-control', class: 'form-control' %>
          <%= f.label :role, "Customer" %><br />
        </div>

        <div class="field">
          <%= f.radio_button :role, 'critic', class: 'form-control' %>
          <%= f.label :role, "Critic" %><br />
        </div>

        <div class="actions">
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<%= will_paginate @users %>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if user.role!= "admin" %>
        <tr>
          <td><%= user.name %>
          <td><%= user.email %>
          <td><%= user.role %>
          <td><%= link_to 'Show', user %></td>
          <% if current_user.role == "admin" %>
            <td><%= link_to 'Edit Role', edit_user_path(user) %></td>
          <% else %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br />
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>New User</h1>
<div class= "row">
  <div class="col-md-4 col-md-offset-4">

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</div>
</div>

app/views/users/show.html.erb
<p>
  <strong>User Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>
<% if current_user.role == "admin" %>
  <%= link_to 'Back', admin_movies_path %>
<% else %>
  <%= link_to 'Back', users_path %>
<% end %>