config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'static_pages/help'

  namespace :admin do
    resources :movies do
      post 'change_status', on: :member
    end
    resources :theatres, :shows
    resources :dashboards, only: [:index]
  end

  resources :movies, only: %i[index show]
  resources :tickets, :movie_interests, except: %i[new edit update]
  resources :reviews, except: %i[edit update]
  devise_for :users, controllers: { registrations: 'myregistrations' }

  resources :users do
    member do
      get 'activate_account'
      get 'activate_user_account'
      post 'activate_account_mail'
    end
  end
end

app/models/movie_interest.rb
class MovieInterest
  include Mongoid::Document
  include Mongoid::Timestamps

  #Indexes
  index({ user_id: 1 }, unique: true)
  index({ movie_id: 1 }, unique: true)
  index({ user_id: 1, movie_id: 1 }, unique: true)

  #Database associations
  belongs_to :movie
  belongs_to :user

  #Validations
  validates :movie_id, uniqueness: { scope: :user_id }
end

app/controllers/movie_interests_controller.rb
class MovieInterestsController < ApplicationController
  authorize_resource :movie_interest
  before_action :set_movie_interest, only: [:destroy]

  def index
    @movie_interests = if current_user.role == 'admin'
                         MovieInterest.where(movie_id: params[:movie_id]).paginate(page: params[:page], per_page: 10)
                       else
                         MovieInterest.where(user_id: current_user.id).paginate(page: params[:page], per_page: 10)
                       end
  end

  def create
    respond_to do |format|
      if MovieInterest.where(movie_id: params[:movie_id], user_id: current_user.id).empty?
        @movie_interest = MovieInterest.new
        @movie_interest.movie_id = params[:movie_id]
        @movie_interest.user_id = current_user.id
        @movie_interest.save
        format.html { redirect_to movies_url, notice: 'Movie was successfully subscribed.' }
        format.json { head :no_content }
      else
        format.html { redirect_back(fallback_location: movies_path) }
        flash[:notice] = 'Already Subscribed'
      end
    end
  end

  def destroy
    @movie_interest.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Unsubscribed.' }
      format.json { head :no_content }
    end
  end

  private
  

  def set_movie_interest
    @movie_interest = MovieInterest.find(params[:id])
  end
end

app/helpers/movie_interests_helper.rb
module MovieInterestsHelper
end

app/views/movie_interests/edit.html.erb
<h1>Editing Movie Interest</h1>
<div class= "row">
  <div class="col-md-4 col-md-offset-4">

<%= render 'form', movie_interest: @movie_interest %>

<%= link_to 'Show', @movie_interest %> |
<%= link_to 'Back', movie_interests_path %>
</div>
</div>

app/views/movie_interests/index.html.erb
<%= will_paginate @movie_interests %>
<h1>Movie Interests</h1>
<% if @movie_interests.any? %>
  <% if current_user.role == "admin" %>
    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Movie</th>
        </tr>
      </thead>

      <tbody>
        <% @movie_interests.each do |movie_interest| %>
          <tr>
            <td><%= movie_interest.user.name %></td>
            <td><%= movie_interest.movie.name %></td>
            <td><%= link_to 'Show User details', user_path(movie_interest.user_id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Movie Name</th>
        </tr>
      </thead>

      <tbody>
        <% @movie_interests.each do |movie_interest| %>
          <tr>
            <td><%= movie_interest.movie.name %></td>
            <td><%= link_to 'Show', movie_path(movie_interest.movie_id) %></td>
            <td><%= link_to 'Unsubscribe', movie_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <br />
<% else %>
  <p> No subscriptions </p>
<% end %>
<%= will_paginate @movie_interests %>

app/views/movie_interests/new.html.erb
<h1>New Movie Interest</h1>
<div class= "row">
  <div class="col-md-4 col-md-offset-4">


<%= render 'form', movie_interest: @movie_interest %>

<%= link_to 'Back', movie_interests_path %>
</div>
</div>