config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'static_pages/help'

  namespace :admin do
    resources :movies do
      post 'change_status', on: :member
    end
    resources :theatres, :shows
    resources :dashboards, only: [:index]
  end

  resources :movies, only: %i[index show]
  resources :tickets, :movie_interests, except: %i[new edit update]
  resources :reviews, except: %i[edit update]
  devise_for :users, controllers: { registrations: 'myregistrations' }

  resources :users do
    member do
      get 'activate_account'
      get 'activate_user_account'
      post 'activate_account_mail'
    end
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :requires_admin
  before_action :set_admin_movie, only: %i[show edit update destroy change_status]
  after_action :send_users_notif, only: %i[change_status]

  def index
    @admin_movies = Movie.all.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render :show }
      format.js {}
    end
  end

  def new
    @admin_movie = Movie.new
  end

  def edit; end

  def create
    @admin_movie = Movie.new(admin_movie_params)
    respond_to do |format|
      if @admin_movie.save
        format.html { redirect_to admin_movies_url, notice: 'Movie was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_movie.update(admin_movie_params)
        format.html { redirect_to admin_movies_url, notice: 'Movie details Updated' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @admin_movie.shows.blank? && @admin_movie.reviews.blank?
        @admin_movie.destroy
        format.html { redirect_to admin_movies_url, notice: 'Movie was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_movies_url, notice: 'Movie cannot be deleted.' }
        format.json { head :no_content }
      end
    end
  end

  def change_status
    @admin_movie.status = 'Now Showing'
    respond_to do |format|
      if @admin_movie.save
        flash[:notice] = 'Successfully updated to Now Showing '
        format.html { redirect_to admin_movies_url }
      end
    end
  end

  private
  

  def set_admin_movie
    @admin_movie = Movie.find(params[:id])
  end

  def admin_movie_params
    params.require(:admin_movie).permit(:name, :summary, :status, :image)
  end

  def send_users_notif
    UserMailer.movie_update(@admin_movie.id.to_s).deliver_later
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :requires_non_admin

  def index
    @movies = Movie.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    @movie = Movie.find(params[:id])
    @shows = Show.where(movie_id: @movie.id).paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/admin/movies/_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">x</button>
      <h4 class="modal-title">Show Details</h4>
    </div>
    <div class="modal-body">
      <%= image_tag(@admin_movie.image_url(:thumb).to_s) %>
      <p>
        <strong>Movie Name:</strong>
        <%= @admin_movie.name %>
      </p>

      <p>
        <strong>Movie Summary</strong>
        <%= @admin_movie.summary %>
      </p>

      <p>
        <strong>Status</strong>
        <%= @admin_movie.status %>
      </p>
      <%= link_to 'Edit', edit_admin_movie_path(@admin_movie) %> |
      <%= link_to 'Back', admin_movies_path %>
    </div>
    </div>
  </div>
</div>

app/views/admin/movies/edit.html.erb
<h1>Editing Movie</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="form-horizontal">
      <%= error_messages_for(@admin_movie) %>
      <%= form_for(@admin_movie, as: :admin_movie, url: admin_movie_path(@admin_movie), html: { method: :patch}) do |f| %> <!-- ###can write otherwise#-->
      
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name , class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :image %><br />
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :summary %>
          <%= f.text_field :summary , class: 'form-control' %>
        </div>

        <div class="radio-inline">
          <%= f.radio_button :status, 'Now Showing' %>
          <%= f.label :status, "Now Showing" %><br />
        </div><br />

        <div class="radio-inline">
          <%= f.radio_button :status, 'Future Release' %>
          <%= f.label :status, "Future Release" %><br />
        </div>

        <div class="actions">
          <%= f.submit "Save" , class: 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to 'Back', admin_movies_path %>
    </div>
 </div>
</div>

app/views/admin/movies/index.html.erb
<%= will_paginate @admin_movies %>
<h1>Admin Movies</h1>
  <table>
    <thead>
      <tr>
        <th>Movie Name</th>
        <th>Movie Summary</th>
        <th>Movie Status</th>
      </tr>
    </thead>
    <tbody>
      <% @admin_movies.each do |admin_movie| %>
        <tr>
          <td><%= admin_movie.name %></td>
          <td><%= admin_movie.summary %></td>
          <td><%= admin_movie.status %></td>
          <td><%= link_to 'Show Details', admin_movie_path(admin_movie),{remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></td>
          <div id="modal-window" class="modal fade" role="dialog"></div>
          <td><%= link_to 'Edit Details', edit_admin_movie_path(admin_movie) %></td>
          <td><%= link_to 'Delete',admin_movie_path(admin_movie), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if admin_movie.status == "Now Showing" %>
            <td><%= link_to 'Add Show', new_admin_show_path(movie: admin_movie.id) %></td>
            <td><%= link_to 'Reviews', reviews_path(:movie => admin_movie.id) %></td>
          <% else %>
            <td><%= link_to 'Change Status', change_status_admin_movie_path(admin_movie.id), method: :post %></td>
            <td><%= link_to 'Show Subscriptions', movie_interests_path(:movie_id => admin_movie.id) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate @admin_movies %>

app/views/admin/movies/new.html.erb
<h1>New Movie</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="form-horizontal">
      <%= error_messages_for(@admin_movie) %>
      <%= form_for(:admin_movie, :url => {:action => 'create'}) do |f| %>
      
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name , class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :summary %>
          <%= f.text_field :summary , class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :image %><br />
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <div class="radio-inline">
          <%= f.radio_button :status, 'Now Showing' %>
          <%= f.label :status, "Now Showing" %><br />
        </div><br />

        <div class="radio-inline">
          <%= f.radio_button :status, 'Future Release' %>
          <%= f.label :status, "Future Release" %><br />
        </div>

        <div class="actions">
          <%= f.submit "Create", class: 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to 'Back', admin_movies_path %>
    </div>
  </div>
</div>

app/views/admin/movies/show.js.erb
$("#modal-window").html("<%= j(render 'modal')%>");
$("#modal-window").modal("show");